<a href="https://colab.research.google.com/github/FaizAlam/ML/blob/main/Weather_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Data Analysis

###The Weather dataset
<hr>
Here, the weather dataset is a time-series data set with per hour information about the weather condition at a particular location. It records temperature, dew point temperature, relative humidity, wind speed, visibility, pressure and conditions

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
filename = '/content/1. Weather Data.csv'

In [4]:
df = pd.read_csv(filename)

In [ ]:
df

             Date/Time  Temp_C  ...  Press_kPa               Weather
0        1/1/2012 0:00    -1.8  ...     101.24                   Fog
1        1/1/2012 1:00    -1.8  ...     101.24                   Fog
2        1/1/2012 2:00    -1.8  ...     101.26  Freezing Drizzle,Fog
3        1/1/2012 3:00    -1.5  ...     101.27  Freezing Drizzle,Fog
4        1/1/2012 4:00    -1.5  ...     101.23                   Fog
...                ...     ...  ...        ...                   ...
8779  12/31/2012 19:00     0.1  ...     100.13                  Snow
8780  12/31/2012 20:00     0.2  ...     100.03                  Snow
8781  12/31/2012 21:00    -0.5  ...      99.95                  Snow
8782  12/31/2012 22:00    -0.2  ...      99.91                  Snow
8783  12/31/2012 23:00     0.0  ...      99.89                  Snow

[8784 rows x 8 columns]

Analyzing data

In [ ]:
df.shape

(8784, 8)

In [ ]:
df.index

RangeIndex(start=0, stop=8784, step=1)

In [ ]:
df.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

In [ ]:
df.dtypes

Date/Time            object
Temp_C              float64
Dew Point Temp_C    float64
Rel Hum_%             int64
Wind Speed_km/h       int64
Visibility_km       float64
Press_kPa           float64
Weather              object
dtype: object

In [ ]:
df['Weather'].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 'Rain,Snow Grains', 'Rain,Snow,Ice Pellets',
       'Snow Showers,Fog', 'Moderate Snow,Blowing Snow'], dtype=object)

In [ ]:
df.nunique()

Date/Time           8784
Temp_C               533
Dew Point Temp_C     489
Rel Hum_%             83
Wind Speed_km/h       34
Visibility_km         24
Press_kPa            518
Weather               50
dtype: int64

In [ ]:
df.count()

Date/Time           8784
Temp_C              8784
Dew Point Temp_C    8784
Rel Hum_%           8784
Wind Speed_km/h     8784
Visibility_km       8784
Press_kPa           8784
Weather             8784
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   object
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

In [ ]:
df.describe()

            Temp_C  Dew Point Temp_C  ...  Visibility_km    Press_kPa
count  8784.000000       8784.000000  ...    8784.000000  8784.000000
mean      8.798144          2.555294  ...      27.664447   101.051623
std      11.687883         10.883072  ...      12.622688     0.844005
min     -23.300000        -28.500000  ...       0.200000    97.520000
25%       0.100000         -5.900000  ...      24.100000   100.560000
50%       9.300000          3.300000  ...      25.000000   101.070000
75%      18.800000         11.800000  ...      25.000000   101.590000
max      33.000000         24.400000  ...      48.300000   103.650000

[8 rows x 6 columns]

### Q1. Find all the unique 'Wind Speed' values in the dataframe

In [ ]:
df['Wind Speed_km/h'].unique()

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2])

In [ ]:
df['Wind Speed_km/h'].nunique()

34

### Q2. Find number of times when the 'Weather is exactly clear'

In [ ]:
#1st way - using value_count
df['Weather'].value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Freezing Drizzle,Fog                          6
Snow,Ice Pellets                              6
Snow,Haze                                     5
Snow Showers,Fog                              4
Freezing Rain,Fog                             4
Freezing Fog                                  4
Rain,Snow,Ice Pellets                         4
Moderate Snow                                 4
Rain,Haze                                     3
Freezing Drizzle,Haze                         3
Thunderstorms,Rain Showers,Fog                3
Thunderstorms,Rain                            3
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Drizzle,Snow                                  2
Freezing Rain,Haze                            2
Rain Showers,Snow Showers                     2
Freezing Rain,Ice Pellets,Fog                 1
Moderate Rain,Fog                             1
Thunderstorms,Heavy Rain Showers              1
Rain,Ice Pellets                              1
Thunderstorms,Rain,Fog                        1
Freezing Rain,Snow Grains                     1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Drizzle,Ice Pellets,Fog                       1
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Rain,Snow Grains                              1
Name: Weather, dtype: int64

In [ ]:
#2nd way- using filtering
df[df['Weather']=='Clear']

             Date/Time  Temp_C  ...  Press_kPa  Weather
67      1/3/2012 19:00   -16.9  ...     101.74    Clear
114     1/5/2012 18:00    -7.1  ...     100.71    Clear
115     1/5/2012 19:00    -9.2  ...     100.80    Clear
116     1/5/2012 20:00    -9.8  ...     100.83    Clear
117     1/5/2012 21:00    -9.0  ...     100.83    Clear
...                ...     ...  ...        ...      ...
8646   12/26/2012 6:00   -13.4  ...     102.47    Clear
8698  12/28/2012 10:00    -6.1  ...     101.27    Clear
8713   12/29/2012 1:00   -11.9  ...     101.31    Clear
8714   12/29/2012 2:00   -11.8  ...     101.33    Clear
8756  12/30/2012 20:00   -13.8  ...     101.52    Clear

[1326 rows x 8 columns]

In [ ]:
#3rd. way - groupby()
df.groupby('Weather').get_group('Clear')

             Date/Time  Temp_C  ...  Press_kPa  Weather
67      1/3/2012 19:00   -16.9  ...     101.74    Clear
114     1/5/2012 18:00    -7.1  ...     100.71    Clear
115     1/5/2012 19:00    -9.2  ...     100.80    Clear
116     1/5/2012 20:00    -9.8  ...     100.83    Clear
117     1/5/2012 21:00    -9.0  ...     100.83    Clear
...                ...     ...  ...        ...      ...
8646   12/26/2012 6:00   -13.4  ...     102.47    Clear
8698  12/28/2012 10:00    -6.1  ...     101.27    Clear
8713   12/29/2012 1:00   -11.9  ...     101.31    Clear
8714   12/29/2012 2:00   -11.8  ...     101.33    Clear
8756  12/30/2012 20:00   -13.8  ...     101.52    Clear

[1326 rows x 8 columns]

### Q3. Find the number of times when the 'wind speed was exactly 4km/h'

In [5]:
df['Wind Speed_km/h']

0        4
1        4
2        7
3        6
4        7
        ..
8779    30
8780    24
8781    28
8782    28
8783    30
Name: Wind Speed_km/h, Length: 8784, dtype: int64

In [6]:
df[df['Wind Speed_km/h']==4]

             Date/Time  Temp_C  ...  Press_kPa       Weather
0        1/1/2012 0:00    -1.8  ...     101.24           Fog
1        1/1/2012 1:00    -1.8  ...     101.24           Fog
96       1/5/2012 0:00    -8.8  ...     100.32          Snow
101      1/5/2012 5:00    -7.0  ...     100.19          Snow
146      1/7/2012 2:00    -8.1  ...     100.15        Cloudy
...                ...     ...  ...        ...           ...
8768   12/31/2012 8:00    -8.6  ...     101.14  Snow Showers
8769   12/31/2012 9:00    -8.1  ...     101.09          Snow
8770  12/31/2012 10:00    -7.4  ...     101.05      Snow,Fog
8772  12/31/2012 12:00    -5.8  ...     100.78          Snow
8773  12/31/2012 13:00    -4.6  ...     100.63          Snow

[474 rows x 8 columns]

In [ ]:
# ans is 474 rows have wind speed 'exactly 4'

### Q4. Find out the null value in data

In [7]:
df.isnull()

      Date/Time  Temp_C  Dew Point Temp_C  ...  Visibility_km  Press_kPa  Weather
0         False   False             False  ...          False      False    False
1         False   False             False  ...          False      False    False
2         False   False             False  ...          False      False    False
3         False   False             False  ...          False      False    False
4         False   False             False  ...          False      False    False
...         ...     ...               ...  ...            ...        ...      ...
8779      False   False             False  ...          False      False    False
8780      False   False             False  ...          False      False    False
8781      False   False             False  ...          False      False    False
8782      False   False             False  ...          False      False    False
8783      False   False             False  ...          False      False    False

[8784 rows x 8 columns]

In [8]:
df.isnull().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

In [ ]:
#No null value

### Q5. Rename the column name 'Weather' of the dataframe to 'Weather Condition'

In [10]:
df.rename(columns={'Weather':'Weather Condition'},inplace=True)

In [11]:
df

             Date/Time  Temp_C  ...  Press_kPa     Weather Condition
0        1/1/2012 0:00    -1.8  ...     101.24                   Fog
1        1/1/2012 1:00    -1.8  ...     101.24                   Fog
2        1/1/2012 2:00    -1.8  ...     101.26  Freezing Drizzle,Fog
3        1/1/2012 3:00    -1.5  ...     101.27  Freezing Drizzle,Fog
4        1/1/2012 4:00    -1.5  ...     101.23                   Fog
...                ...     ...  ...        ...                   ...
8779  12/31/2012 19:00     0.1  ...     100.13                  Snow
8780  12/31/2012 20:00     0.2  ...     100.03                  Snow
8781  12/31/2012 21:00    -0.5  ...      99.95                  Snow
8782  12/31/2012 22:00    -0.2  ...      99.91                  Snow
8783  12/31/2012 23:00     0.0  ...      99.89                  Snow

[8784 rows x 8 columns]

### Q6. What is the mean visibility?

In [12]:
df['Visibility_km'].mean

<bound method Series.mean of 0        8.0
1        8.0
2        4.0
3        4.0
4        4.8
        ...
8779     9.7
8780     9.7
8781     4.8
8782     9.7
8783    11.3
Name: Visibility_km, Length: 8784, dtype: float64>

In [13]:
df['Visibility_km'].mean()

27.66444672131151

### Q7. What is the standard deviation of presssure in this data?

In [14]:
df['Press_kPa'].std()

0.8440047459486474

### Q8. What is the variance of 'Relative humidity' in this data?

In [15]:
df['Rel Hum_%'].var()

286.2485501984998

### Q9. Find all instances when 'snow' was recorded

In [16]:
df.head(2)

       Date/Time  Temp_C  ...  Press_kPa  Weather Condition
0  1/1/2012 0:00    -1.8  ...     101.24                Fog
1  1/1/2012 1:00    -1.8  ...     101.24                Fog

[2 rows x 8 columns]

In [18]:
df[df['Weather Condition']=='Snow'].count()

Date/Time            390
Temp_C               390
Dew Point Temp_C     390
Rel Hum_%            390
Wind Speed_km/h      390
Visibility_km        390
Press_kPa            390
Weather Condition    390
dtype: int64

In [19]:
#str contains
df[df['Weather Condition'].str.contains('Snow')]

             Date/Time  Temp_C  ...  Press_kPa  Weather Condition
41      1/2/2012 17:00    -2.1  ...      99.66       Snow Showers
44      1/2/2012 20:00    -5.6  ...     100.07       Snow Showers
45      1/2/2012 21:00    -5.8  ...     100.15       Snow Showers
47      1/2/2012 23:00    -7.4  ...     100.27       Snow Showers
48       1/3/2012 0:00    -9.0  ...     100.35       Snow Showers
...                ...     ...  ...        ...                ...
8779  12/31/2012 19:00     0.1  ...     100.13               Snow
8780  12/31/2012 20:00     0.2  ...     100.03               Snow
8781  12/31/2012 21:00    -0.5  ...      99.95               Snow
8782  12/31/2012 22:00    -0.2  ...      99.91               Snow
8783  12/31/2012 23:00     0.0  ...      99.89               Snow

[583 rows x 8 columns]

In [21]:
df[df['Weather Condition'].str.contains('Snow')].tail(20)

             Date/Time  Temp_C  ...  Press_kPa  Weather Condition
8740   12/30/2012 4:00    -9.3  ...     100.28           Snow,Fog
8741   12/30/2012 5:00    -9.1  ...     100.32           Snow,Fog
8742   12/30/2012 6:00    -9.3  ...     100.39           Snow,Fog
8767   12/31/2012 7:00    -9.3  ...     101.19       Snow Showers
8768   12/31/2012 8:00    -8.6  ...     101.14       Snow Showers
8769   12/31/2012 9:00    -8.1  ...     101.09               Snow
8770  12/31/2012 10:00    -7.4  ...     101.05           Snow,Fog
8771  12/31/2012 11:00    -6.7  ...     100.93               Snow
8772  12/31/2012 12:00    -5.8  ...     100.78               Snow
8773  12/31/2012 13:00    -4.6  ...     100.63               Snow
8774  12/31/2012 14:00    -3.4  ...     100.57               Snow
8775  12/31/2012 15:00    -2.3  ...     100.47               Snow
8776  12/31/2012 16:00    -1.4  ...     100.40               Snow
8777  12/31/2012 17:00    -1.1  ...     100.30               Snow
8778  12/31/2012 18:00    -1.3  ...     100.19               Snow
8779  12/31/2012 19:00     0.1  ...     100.13               Snow
8780  12/31/2012 20:00     0.2  ...     100.03               Snow
8781  12/31/2012 21:00    -0.5  ...      99.95               Snow
8782  12/31/2012 22:00    -0.2  ...      99.91               Snow
8783  12/31/2012 23:00     0.0  ...      99.89               Snow

[20 rows x 8 columns]

In [ ]:
# this 'str contains' shows all the rows which contains 'Snow' as a word.

### Q10. Find all instances when 'wind speed is above 24' and 'visibility is 25'

In [25]:
df[(df['Wind Speed_km/h']>24) & (df['Visibility_km']==25)]

             Date/Time  Temp_C  ...  Press_kPa  Weather Condition
23      1/1/2012 23:00     5.3  ...      99.31             Cloudy
24       1/2/2012 0:00     5.2  ...      99.26       Rain Showers
25       1/2/2012 1:00     4.6  ...      99.26             Cloudy
26       1/2/2012 2:00     3.9  ...      99.26      Mostly Cloudy
27       1/2/2012 3:00     3.7  ...      99.30      Mostly Cloudy
...                ...     ...  ...        ...                ...
8705  12/28/2012 17:00    -8.6  ...     101.34       Mainly Clear
8753  12/30/2012 17:00   -12.1  ...     101.26       Mainly Clear
8755  12/30/2012 19:00   -13.4  ...     101.47       Mainly Clear
8759  12/30/2012 23:00   -12.1  ...     101.52      Mostly Cloudy
8760   12/31/2012 0:00   -11.1  ...     101.51             Cloudy

[308 rows x 8 columns]

### Q11. What is the mean value of each column against each 'Weather Condition'?

In [26]:
df.groupby('Weather Condition').mean()

                                            Temp_C  ...   Press_kPa
Weather Condition                                   ...
Clear                                     6.825716  ...  101.587443
Cloudy                                    7.970544  ...  100.911441
Drizzle                                   7.353659  ...  100.435366
Drizzle,Fog                               8.067500  ...  100.786625
Drizzle,Ice Pellets,Fog                   0.400000  ...  100.790000
Drizzle,Snow                              1.050000  ...  100.890000
Drizzle,Snow,Fog                          0.693333  ...   99.281333
Fog                                       4.303333  ...  101.184067
Freezing Drizzle                         -5.657143  ...  100.202857
Freezing Drizzle,Fog                     -2.533333  ...  100.441667
Freezing Drizzle,Haze                    -5.433333  ...  100.316667
Freezing Drizzle,Snow                    -5.109091  ...  100.520909
Freezing Fog                             -7.575000  ...  102.320000
Freezing Rain                            -3.885714  ...   99.647143
Freezing Rain,Fog                        -2.225000  ...   99.945000
Freezing Rain,Haze                       -4.900000  ...  100.375000
Freezing Rain,Ice Pellets,Fog            -2.600000  ...  100.950000
Freezing Rain,Snow Grains                -5.000000  ...   98.560000
Haze                                     -0.200000  ...  101.482500
Mainly Clear                             12.558927  ...  101.248832
Moderate Rain,Fog                         1.700000  ...   99.980000
Moderate Snow                            -5.525000  ...  100.275000
Moderate Snow,Blowing Snow               -5.450000  ...  100.570000
Mostly Cloudy                            10.574287  ...  101.025288
Rain                                      9.786275  ...  100.233333
Rain Showers                             13.722340  ...  100.404043
Rain Showers,Fog                         12.800000  ...   99.830000
Rain Showers,Snow Showers                 2.150000  ...  101.100000
Rain,Fog                                  8.273276  ...  100.500862
Rain,Haze                                 4.633333  ...  100.540000
Rain,Ice Pellets                          0.600000  ...  100.120000
Rain,Snow                                 1.055556  ...   99.951111
Rain,Snow Grains                          1.900000  ...  100.600000
Rain,Snow,Fog                             0.800000  ...  100.730000
Rain,Snow,Ice Pellets                     1.100000  ...  100.105000
Snow                                     -4.524103  ...  100.536103
Snow Pellets                              0.700000  ...   99.700000
Snow Showers                             -3.506667  ...  100.963500
Snow Showers,Fog                        -10.675000  ...  101.292500
Snow,Blowing Snow                        -5.410526  ...   99.704737
Snow,Fog                                 -5.075676  ...  100.688649
Snow,Haze                                -4.020000  ...  100.782000
Snow,Ice Pellets                         -1.883333  ...  100.548333
Thunderstorms                            24.150000  ...  100.230000
Thunderstorms,Heavy Rain Showers         10.900000  ...  100.260000
Thunderstorms,Moderate Rain Showers,Fog  19.600000  ...  100.010000
Thunderstorms,Rain                       20.433333  ...  100.420000
Thunderstorms,Rain Showers               20.037500  ...  100.233750
Thunderstorms,Rain Showers,Fog           21.600000  ...  100.063333
Thunderstorms,Rain,Fog                   20.600000  ...  100.080000

[50 rows x 6 columns]

-  The higher the humidity, the wetter it feels outside
-  The higher the dew point rises, the greater the amount of moisture in the air
- When a low-pressure system moves into an area, it usually leads to cloudiness, wind, and precipitation. High-pressure systems usually lead to fair, calm weather.
- Visibility is clearer when weather is clean

### Q12. What is the minimum and maximum values of each columns against each 'Weather Condtion'?

In [28]:
df.groupby('Weather Condition').min()

                                                Date/Time  ...  Press_kPa
Weather Condition                                          ...
Clear                                      1/11/2012 1:00  ...      99.52
Cloudy                                     1/1/2012 17:00  ...      98.39
Drizzle                                   1/23/2012 21:00  ...      97.84
Drizzle,Fog                               1/23/2012 20:00  ...      98.65
Drizzle,Ice Pellets,Fog                   12/17/2012 9:00  ...     100.79
Drizzle,Snow                             12/17/2012 15:00  ...     100.63
Drizzle,Snow,Fog                         12/18/2012 21:00  ...      97.79
Fog                                         1/1/2012 0:00  ...      98.31
Freezing Drizzle                          1/13/2012 10:00  ...      98.44
Freezing Drizzle,Fog                        1/1/2012 2:00  ...      98.74
Freezing Drizzle,Haze                      2/1/2012 11:00  ...     100.28
Freezing Drizzle,Snow                      1/13/2012 3:00  ...      99.19
Freezing Fog                               1/22/2012 6:00  ...     101.97
Freezing Rain                             1/13/2012 11:00  ...      98.22
Freezing Rain,Fog                         1/17/2012 23:00  ...      98.32
Freezing Rain,Haze                         2/1/2012 14:00  ...     100.34
Freezing Rain,Ice Pellets,Fog             12/17/2012 3:00  ...     100.95
Freezing Rain,Snow Grains                  1/13/2012 9:00  ...      98.56
Haze                                      1/22/2012 12:00  ...     100.35
Mainly Clear                              1/10/2012 11:00  ...      98.67
Moderate Rain,Fog                         12/10/2012 8:00  ...      99.98
Moderate Snow                             1/12/2012 15:00  ...      99.88
Moderate Snow,Blowing Snow               12/27/2012 10:00  ...     100.50
Mostly Cloudy                              1/1/2012 16:00  ...      98.36
Rain                                       1/1/2012 18:00  ...      97.52
Rain Showers                               1/1/2012 22:00  ...      98.51
Rain Showers,Fog                          10/20/2012 3:00  ...      99.83
Rain Showers,Snow Showers                  11/4/2012 8:00  ...     101.09
Rain,Fog                                  1/23/2012 18:00  ...      98.61
Rain,Haze                                  3/13/2012 7:00  ...     100.50
Rain,Ice Pellets                          12/18/2012 5:00  ...     100.12
Rain,Snow                                  1/10/2012 5:00  ...      98.18
Rain,Snow Grains                          12/21/2012 0:00  ...     100.60
Rain,Snow,Fog                             12/8/2012 21:00  ...     100.73
Rain,Snow,Ice Pellets                     12/21/2012 1:00  ...      99.85
Snow                                       1/10/2012 1:00  ...      97.75
Snow Pellets                             11/24/2012 15:00  ...      99.70
Snow Showers                               1/12/2012 7:00  ...      99.49
Snow Showers,Fog                          12/26/2012 9:00  ...     100.63
Snow,Blowing Snow                         1/13/2012 21:00  ...      98.11
Snow,Fog                                 12/16/2012 15:00  ...      99.38
Snow,Haze                                  2/1/2012 17:00  ...     100.61
Snow,Ice Pellets                          12/10/2012 3:00  ...      99.40
Thunderstorms                              7/16/2012 1:00  ...      99.84
Thunderstorms,Heavy Rain Showers           5/29/2012 6:00  ...     100.26
Thunderstorms,Moderate Rain Showers,Fog    7/17/2012 6:00  ...     100.01
Thunderstorms,Rain                        5/25/2012 20:00  ...     100.19
Thunderstorms,Rain Showers                5/29/2012 16:00  ...      99.65
Thunderstorms,Rain Showers,Fog             6/29/2012 3:00  ...      99.71
Thunderstorms,Rain,Fog                     7/17/2012 5:00  ...     100.08

[50 rows x 7 columns]

In [29]:
df.groupby('Weather Condition').max()

                                                Date/Time  ...  Press_kPa
Weather Condition                                          ...
Clear                                       9/9/2012 5:00  ...     103.63
Cloudy                                     9/9/2012 23:00  ...     103.65
Drizzle                                    9/30/2012 3:00  ...     101.56
Drizzle,Fog                                9/30/2012 2:00  ...     102.07
Drizzle,Ice Pellets,Fog                   12/17/2012 9:00  ...     100.79
Drizzle,Snow                             12/19/2012 18:00  ...     101.15
Drizzle,Snow,Fog                          12/22/2012 3:00  ...     100.15
Fog                                        9/22/2012 0:00  ...     103.04
Freezing Drizzle                            2/1/2012 5:00  ...     101.02
Freezing Drizzle,Fog                      12/10/2012 5:00  ...     101.27
Freezing Drizzle,Haze                      2/1/2012 13:00  ...     100.36
Freezing Drizzle,Snow                      3/2/2012 12:00  ...     101.18
Freezing Fog                               3/17/2012 6:00  ...     102.85
Freezing Rain                               2/1/2012 7:00  ...     101.00
Freezing Rain,Fog                         12/17/2012 1:00  ...     101.01
Freezing Rain,Haze                         2/1/2012 15:00  ...     100.41
Freezing Rain,Ice Pellets,Fog             12/17/2012 3:00  ...     100.95
Freezing Rain,Snow Grains                  1/13/2012 9:00  ...      98.56
Haze                                      3/13/2012 23:00  ...     102.97
Mainly Clear                                9/9/2012 9:00  ...     103.59
Moderate Rain,Fog                         12/10/2012 8:00  ...      99.98
Moderate Snow                             12/27/2012 9:00  ...     100.67
Moderate Snow,Blowing Snow               12/27/2012 12:00  ...     100.64
Mostly Cloudy                               9/9/2012 2:00  ...     103.65
Rain                                        9/5/2012 2:00  ...     102.26
Rain Showers                               9/8/2012 16:00  ...     102.31
Rain Showers,Fog                          10/20/2012 3:00  ...      99.83
Rain Showers,Snow Showers                 12/5/2012 10:00  ...     101.11
Rain,Fog                                  9/30/2012 23:00  ...     101.77
Rain,Haze                                  3/13/2012 9:00  ...     100.61
Rain,Ice Pellets                          12/18/2012 5:00  ...     100.12
Rain,Snow                                  4/23/2012 3:00  ...     101.07
Rain,Snow Grains                          12/21/2012 0:00  ...     100.60
Rain,Snow,Fog                             12/8/2012 21:00  ...     100.73
Rain,Snow,Ice Pellets                     12/21/2012 5:00  ...     100.47
Snow                                       4/27/2012 9:00  ...     102.73
Snow Pellets                             11/24/2012 15:00  ...      99.70
Snow Showers                               3/4/2012 21:00  ...     102.50
Snow Showers,Fog                         12/29/2012 13:00  ...     102.52
Snow,Blowing Snow                          2/25/2012 9:00  ...     100.62
Snow,Fog                                  3/14/2012 19:00  ...     102.07
Snow,Haze                                  2/1/2012 21:00  ...     100.99
Snow,Ice Pellets                            3/3/2012 4:00  ...     100.96
Thunderstorms                              7/4/2012 16:00  ...     100.62
Thunderstorms,Heavy Rain Showers           5/29/2012 6:00  ...     100.26
Thunderstorms,Moderate Rain Showers,Fog    7/17/2012 6:00  ...     100.01
Thunderstorms,Rain                        7/23/2012 18:00  ...     100.83
Thunderstorms,Rain Showers                  9/8/2012 4:00  ...     101.06
Thunderstorms,Rain Showers,Fog            7/31/2012 20:00  ...     100.64
Thunderstorms,Rain,Fog                     7/17/2012 5:00  ...     100.08

[50 rows x 7 columns]

### Q13. Show all the records where weather condtion is Fog.

In [33]:
df[df['Weather Condition'].str.contains('Fog')]

             Date/Time  Temp_C  ...  Press_kPa     Weather Condition
0        1/1/2012 0:00    -1.8  ...     101.24                   Fog
1        1/1/2012 1:00    -1.8  ...     101.24                   Fog
2        1/1/2012 2:00    -1.8  ...     101.26  Freezing Drizzle,Fog
3        1/1/2012 3:00    -1.5  ...     101.27  Freezing Drizzle,Fog
4        1/1/2012 4:00    -1.5  ...     101.23                   Fog
...                ...     ...  ...        ...                   ...
8739   12/30/2012 3:00    -9.1  ...     100.30              Snow,Fog
8740   12/30/2012 4:00    -9.3  ...     100.28              Snow,Fog
8741   12/30/2012 5:00    -9.1  ...     100.32              Snow,Fog
8742   12/30/2012 6:00    -9.3  ...     100.39              Snow,Fog
8770  12/31/2012 10:00    -7.4  ...     101.05              Snow,Fog

[426 rows x 8 columns]

428 rows where weather condition is Fog

### Q14. Find all the instances where 'Weather is clear' or 'visibility is above 40'

In [35]:
df[(df['Weather Condition']=='Clear') | (df['Visibility_km']>40)]

             Date/Time  Temp_C  ...  Press_kPa  Weather Condition
67      1/3/2012 19:00   -16.9  ...     101.74              Clear
106     1/5/2012 10:00    -6.0  ...     100.45       Mainly Clear
107     1/5/2012 11:00    -5.6  ...     100.41       Mainly Clear
108     1/5/2012 12:00    -4.7  ...     100.38       Mainly Clear
109     1/5/2012 13:00    -4.4  ...     100.40       Mainly Clear
...                ...     ...  ...        ...                ...
8749  12/30/2012 13:00   -12.4  ...     100.92      Mostly Cloudy
8750  12/30/2012 14:00   -11.8  ...     100.96       Mainly Clear
8751  12/30/2012 15:00   -11.3  ...     101.05       Mainly Clear
8752  12/30/2012 16:00   -11.4  ...     101.15       Mainly Clear
8756  12/30/2012 20:00   -13.8  ...     101.52              Clear

[3027 rows x 8 columns]

### Q15. Find all instances when :
A) 'Weather is clear and relative humidity is more than 50

B) 'Visibility' is above 40

In [38]:
#A
df[(df['Weather Condition']=='Clear') & (df['Rel Hum_%']>50) | (df['Visibility_km']>40)]

             Date/Time  Temp_C  ...  Press_kPa  Weather Condition
106     1/5/2012 10:00    -6.0  ...     100.45       Mainly Clear
107     1/5/2012 11:00    -5.6  ...     100.41       Mainly Clear
108     1/5/2012 12:00    -4.7  ...     100.38       Mainly Clear
109     1/5/2012 13:00    -4.4  ...     100.40       Mainly Clear
110     1/5/2012 14:00    -5.1  ...     100.46       Mainly Clear
...                ...     ...  ...        ...                ...
8749  12/30/2012 13:00   -12.4  ...     100.92      Mostly Cloudy
8750  12/30/2012 14:00   -11.8  ...     100.96       Mainly Clear
8751  12/30/2012 15:00   -11.3  ...     101.05       Mainly Clear
8752  12/30/2012 16:00   -11.4  ...     101.15       Mainly Clear
8756  12/30/2012 20:00   -13.8  ...     101.52              Clear

[2921 rows x 8 columns]